#!/bin/bash

echo "Compiling..."

rm -r build/*

mkdir -p build/parser
mkdir -p build/package

echo "Compiling SCSS styles"

# Style
# compass compile --sass-dir src/style/ --css-dir package/style/

# All files
# node_modules/.bin/coffee --compile --bare --output build src

echo "Compiling PEG.js"

# Apply parser
node_modules/.bin/pegjs \
  --export-var "module.exports" \
  src/parser/apply.pegjs \
  build/parser/apply.js

# Filter parser
node_modules/.bin/pegjs \
  --export-var "module.exports" \
  src/parser/filter.pegjs \
  build/parser/filter.js

# Parts
mkdir -p package

# TypeScript
echo "Compiling TypeScript basics"
node_modules/.bin/tsc -m commonjs --noImplicitAny -d --outDir build src/*.ts

echo "Compiling query"
node_modules/.bin/tsc -m commonjs --noImplicitAny -d --outDir build src/query/*.ts

echo "Compiling locators"
node_modules/.bin/tsc -m commonjs --noImplicitAny -d --outDir build src/locator/*.ts

echo "Compiling requesters"
node_modules/.bin/tsc -m commonjs --noImplicitAny -d --outDir build src/requester/*.ts

echo "Compiling drivers"
node_modules/.bin/tsc -m commonjs --noImplicitAny -d --outDir build src/driver/*.ts

echo "Compiling render"
node_modules/.bin/tsc -m commonjs --noImplicitAny -d --outDir build src/render/*.ts

echo "Compiling workers"
node_modules/.bin/tsc -m commonjs --noImplicitAny -d --outDir build src/worker/*.ts

# echo "Bundle type definitions"
# node dts-bundle.js

# browserify build/driver/index.js \
#   -o package/driver.js \
#   --ignore async \
#   --standalone driver
#
# browserify build/render/index.js \
#   -o package/render.js \
#   --standalone render
#
# browserify build/query/index.js \
#   -o package/query.js \
#   --standalone query
#
# # All in one
# browserify build/facet.js \
#   -o package/facet.js \
#   --standalone facet
#
# # Web workers
# browserify build/worker/simpleDriverWorker.js \
#   -o package/simpleDriverWorker.js
