#!/bin/bash
compass compile --sass-dir src/style/ --css-dir target/
coffee --compile --bare --output target src/server.coffee src/requester/*
coffee --compile --bare --output target src/driver/*
coffee --compile --bare --output target src/converter/*.coffee

node_modules/pegjs/bin/pegjs --export-var "applyParser" src/converter/applyParser.pegjs target/applyParser.js

coffee --compile --bare --output target --join target/facet.js \
  src/facet/_start.coffee \
  src/facet/init.coffee \
  src/facet/utils.coffee \
  src/facet/interval.coffee \
  src/facet/segment.coffee \
  src/facet/filter.coffee \
  src/facet/split.coffee \
  src/facet/apply.coffee \
  src/facet/combine.coffee \
  src/facet/use.coffee \
  src/facet/scale.coffee \
  src/facet/layout.coffee \
  src/facet/transform.coffee \
  src/facet/plot.coffee \
  src/facet/connector.coffee \
  src/facet/facet.coffee \
  src/facet/proxy.coffee \
  src/facet/_end.coffee

coffee --compile --bare --output target --join target/query.js \
  src/query/_start.coffee \
  src/query/filter.coffee \
  src/query/split.coffee \
  src/query/apply.coffee \
  src/query/combine.coffee \
  src/query/query.coffee \
  src/query/_end.coffee
