#!/bin/bash

rm -rf build/*
mkdir -p build

node_modules/.bin/tsc --noImplicitAny --noEmitOnError --declaration --removeComments --out build/facet.js \
  src/init.ts \
  \
  src/core/datatypes/common.ts \
  src/core/datatypes/dataset.ts \
  src/core/datatypes/numberRange.ts \
  src/core/datatypes/set.ts \
  src/core/datatypes/shape.ts \
  src/core/datatypes/timeRange.ts \
  \
  src/core/expressions/baseExpression.ts \
  src/core/expressions/unaryExpression.ts \
  src/core/expressions/binaryExpression.ts \
  src/core/expressions/naryExpression.ts \
  src/core/expressions/actionsExpression.ts \
  src/core/expressions/addExpression.ts \
  src/core/expressions/aggregateExpression.ts \
  src/core/expressions/andExpression.ts \
  src/core/expressions/concatExpression.ts \
  src/core/expressions/greaterThanExpression.ts \
  src/core/expressions/greaterThanOrEqualExpression.ts \
  src/core/expressions/inExpression.ts \
  src/core/expressions/isExpression.ts \
  src/core/expressions/labelExpression.ts \
  src/core/expressions/lessThanExpression.ts \
  src/core/expressions/lessThanOrEqualExpression.ts \
  src/core/expressions/literalExpression.ts \
  src/core/expressions/matchExpression.ts \
  src/core/expressions/multiplyExpression.ts \
  src/core/expressions/negateExpression.ts \
  src/core/expressions/notExpression.ts \
  src/core/expressions/numberBucketExpression.ts \
  src/core/expressions/orExpression.ts \
  src/core/expressions/reciprocateExpression.ts \
  src/core/expressions/refExpression.ts \
  src/core/expressions/timeBucketExpression.ts \
  src/core/expressions/timeOffsetExpression.ts \
  \
  src/core/actions/baseAction.ts \
  src/core/actions/applyAction.ts \
  src/core/actions/defAction.ts \
  src/core/actions/filterAction.ts \
  src/core/actions/limitAction.ts \
  src/core/actions/sortAction.ts \
  \
  src/extra/simpleLocator.ts \
  src/extra/retryRequester.ts \
  \
  src/legacy/query/common.ts \
  src/legacy/query/apply.ts \
  src/legacy/query/applySimplifier.ts \
  src/legacy/query/attributeMeta.ts \
  src/legacy/query/combine.ts \
  src/legacy/query/condensedCommand.ts \
  src/legacy/query/filter.ts \
  src/legacy/query/dataset.ts \
  src/legacy/query/options.ts \
  src/legacy/query/query.ts \
  src/legacy/query/segmentFilter.ts \
  src/legacy/query/segmentTree.ts \
  src/legacy/query/sort.ts \
  src/legacy/query/split.ts \
  \
  src/legacy/driver/common.ts \
  src/legacy/driver/driverUtil.ts \
  src/legacy/driver/druidDriver.ts \
  src/legacy/driver/fractalCache.ts \
  src/legacy/driver/mySqlDriver.ts \
  src/legacy/driver/nativeDriver.ts \
  \
  src/core/driver/legacyDriver.ts \
  \
  src/exports.ts \
  && \
  sed s/_delete_me_// build/facet.js > tmp && \
  mv -f tmp build/facet.js;

#src/legacy/driver/proxyDriver.ts \

