#!/bin/bash
mkdir -p build/parser
mkdir -p build/package

# Style
compass compile --sass-dir src/style/ --css-dir build/style/

# All files
coffee --compile --bare --output build src

# Apply parser
node_modules/pegjs/bin/pegjs \
  --export-var "module.exports" \
  src/parser/apply.pegjs \
  build/parser/apply.js

# Parts
browserify build/driver/index.js \
  -o build/package/driver.js \
  --ignore async \
  --standalone driver

browserify build/render/index.js \
  -o build/package/render.js \
  --standalone render

browserify build/query/index.js \
  -o build/package/query.js \
  --standalone query

# All in one
browserify build/facet.js \
  -o build/package/facet.js \
  --standalone facet

# Web workers
browserify build/worker/simpleDriverWorker.js \
  -o build/package/simpleDriverWorker.js
