#!/bin/bash

rm -rf build/*

# TypeScript
node_modules/.bin/tsc --noImplicitAny --noEmitOnError --declaration --out build/facet.js \
  src/datatypes/* \
  src/expressions/* \
  src/actions/* \
  src/exports.ts
