#!/bin/bash

if grep -rq 'describe\.only' ./test
  then
    echo "describe.only found. Please update your test"
    exit 1
fi

if grep -rq 'it\.only' ./test
  then
    echo "it.only found. Please update your test"
    exit 1
fi

mocha \
  test/core/* \
  test/extra/* \
  test/legacy/query/* \
  test/legacy/driver/fractalCache.mocha.coffee \
  test/legacy/driver/nativeDriver.mocha.coffee \
  test/legacy/driver/driverUtil.mocha.coffee \
  test/legacy/driver/fractalCacheHelpers.mocha.coffee;

# Commented out because these tests require some extra setup like Druid endpoints and mysql server
# mocha test/legacy/driver/diamonds.mocha.coffee
# mocha test/legacy/driver/druidDriver.mocha.coffee
# mocha test/legacy/driver/mySqlDriver.mocha.coffee
# mocha test/legacy/driver/driverErrors.mocha.coffee
# mocha test/legacy/driver/wikiDay.mocha.coffee
